### PR TITLE
Add Github Actions build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/amazon-sagemaker-operator-for-k8s/actions/runs/401899454

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Hello Gabor,

Thank you for your contribution. Would you mind providing some context around why you hope to include a github actions build script for the operators? We currently have an automated build and unit test hook running in CodeBuild for every PR, would that suffice?

**Comment by gliptak** [comment]
@RedbackThomson when clicking on CodeBuild link, I get a login screen and cannot see details. Unless the CodeBuild results are open to public, the Github Actions offer better integration and visbility.

image

**Comment by RedbackThomson** [comment]
Completely understandable. Unfortunately there isn't an option yet for exporting CodeBuild logs to a publicly accessible location. 
I think for us to support Github actions we would need a little more work to ensure that it builds correctly and runs tests in the same way as the CodeBuild specifications. (Found in the `codebuild/` directory)

**Comment by gliptak** [comment]
@RedbackThomson thank you for the pointers. I still see value in a partial check being publicly visible and i understand if that is not the direction you are taking.

**Pull request closed without merging**
